### PR TITLE
Added application.properties to the gitignore file

### PR DESCRIPTION
**Pull request by mynameisandreee**

### CODE REVIEW

**Review by Warmedpie — CHANGES_REQUESTED** [review]
NIT: *.properties

**Review by Warmedpie — CHANGES_REQUESTED** [review]
This should be *.properties, not just .properties

**Review by Warmedpie — DISMISSED** [review]
*.properties is good.

**Review by Warmedpie — APPROVED** [review]
*.properties is good.

**Review by wallclockbuilder — APPROVED** [review]

**Review by LiquidPlummer — APPROVED** [review]
Hey this stuff looks good. I thought I already had application.properties in a gitignore somewhere. Was it not working? 

Either way I approve

**Pull request merged**
