### PR TITLE
Alden history frontend

### PR DESCRIPTION
**Pull request by Warmedpie**
No styling yet
the component is on "/order"
I just use dummy data for the testing
reformatted some of Braxton's interfaces into the types folder

### CODE REVIEW

**Comment by wsrn829** [comment]
Hey @Warmedpie, could you call me on Teams when you have time? I'm somehow getting a 403 error when trying to register on your branch. Would you mind taking a look? Thanks!

**Review by cdedpe — COMMENTED** [review]
Hey @Warmedpie, could you call me on Teams when you have time? I'm somehow getting a 403 error when trying to register on your branch. Would you mind taking a look? Thanks!  --- Never mind, I opened a different local repo. :p

**Review by cdedpe — APPROVED** [review]
Hey Alden, I was able to see your dummy data both in the console and the browser on my end. Thanks for simplifying the testing. :)

**Review by mynameisandreee — APPROVED** [review]
LGTM

**Pull request merged**
