### PR TITLE
corrected login request for cookie handling and added logout to clean up any stored token

### PR DESCRIPTION
**Pull request by angelaW879**

### CODE REVIEW

**Review by cdedpe — APPROVED** [review]
Tested locally, and everything is working as expected on my end.

**Comment by Warmedpie** [comment]
This mostly looks good, just for quick clarification; it looks like you store a variable "token" in Auth context, and pass it to the children, but it appears to never be used in the parent or children elements. It looks like you set it and unset it, but never use it. I could be missing something, so a quick clarification comment would be helpful.

**Review by wallclockbuilder — APPROVED** [review]
LGTM!

**Comment by angelaW879** [comment]
> This mostly looks good, just for quick clarification; it looks like you store a variable "token" in Auth context, and pass it to the children, but it appears to never be used in the parent or children elements. It looks like you set it and unset it, but never use it. I could be missing something, so a quick clarification comment would be helpful.

The reason I stored the token is because I wanted to check if different user gets returned a new token after they login. We were having an issue where the token was not being cleared properly, and if you login for the first time, that token will stay in the cookie and when other user login, they will use the old token from the previous user. Also, I tested that without passing in the token in the header and just use "credentials: include" is sufficient for making fetch request that requires token authentication.

**Pull request merged**
