### PR TITLE
Auth login register fetch other user

### PR DESCRIPTION
**Pull request by angelaW879**
It's working on my end, can someone else test this branch before merging please?

### CODE REVIEW

**Review by cdedpe — COMMENTED** [review]
Hey Angela, I tried to test it on my end just now but couldn't run the server because I don't have your JWT secret key. Can you send it to my email address - wsrn829@gmail.com? Impressed by your speed though. Great work.

**Comment by angelaW879** [comment]
I added the key to our Teams general channel, thanks for helping to test it!

**Comment by cdedpe** [comment]
> I added the key to our Teams general channel, thanks for helping to test it!

That's perfect because everyone will need it. However, I wasn't able to see the key in our Teams general channel somehow. I'll check with you tomorrow. :) You're welcome, and thanks again for your help!

**Comment by mynameisandreee** [comment]
This is the key from Angela . Sarina she posted it in General chat on teams
. but i will paste it here, you can add it to your application.properties .
I will edit this file tomorrow because im emailing from my phone
—————
jwt.secret=K/6j98GRfrtmVn0nH/lQc/C5k4JQJeVRcJ2PiSwgAf7sdJ0PhFQZ/oh2hXgXwY3POD4EAVziou5Bdfr3Yb3HgQgtXb0QHJIg8FiHlPZTed7KJgL1dRJwXfdF6yS4TiZcKH2gdtBSqfZpC7FqVo7mtRiF3T87J1PtdlkR5poZuc4Iq8TXuFQ+QnD2prkf/0M/C4Cv6jPbqO2YNFr5F4q+WydNQv2shhT/e8PpDGfzzzyCNxd4VG/Sx4p6KoMfzSkINPaDbr4RWa1m/jC6FSbcNOeUVqVj9ttSsmR8nmYNuGpmTtoD8S98zC3Hr6DQF38cA3DxfuD8UuKshBClFvkaAy7oI3s5rkXkXmZG1/s+JAXLJCE=

**Comment by cdedpe** [comment]
Thank you so much, Anthony! I’ll probably need Kyle to check my Teams settings & I’ll also need the entire application.properties tomorrow. Good night!

**Review by mynameisandreee — COMMENTED** [review]
I tested your branch . 
 I had to add this  into the build in pom file to run it 
<resources>
			<resource>
				<directory>src/resources</directory>
			</resource>
</resources>

and it also giving me 403 error when i tested the register

**Review by wallclockbuilder — APPROVED** [review]
Lgtm.

**Review by cdedpe — DISMISSED** [review]
Impressive work. Code looks good. But I'll need all the custom key-value pairs you added to the application.properties file before I approve this pull request. Thank you.

**Review by SaintKiri — APPROVED** [review]

**Review by mynameisandreee — APPROVED** [review]
This is working

**Review by cdedpe — APPROVED** [review]
Working on my end too!

**Comment by wallclockbuilder** [comment]
Its merged.

**Comment by cdedpe** [comment]
Perfect!!

**Pull request merged**
