### PR TITLE
Britt

### PR DESCRIPTION
**Pull request by brittmol**

### CODE REVIEW

**Review by wallclockbuilder — CHANGES_REQUESTED** [review]
This pull request has a lot of temporary commits that should be replaced with the final commit.
You might want to squash your git history into one commit that summarizes the Pull Request.

**Comment by brittmol** [comment]
Merged Brittany and Angela's changes in models/user.java
see most recent commit comments
changes:
long userId --> integer userId
isActive --> banned

**Comment by wallclockbuilder** [comment]
I did notice there is a squash and merge button after everything is approved so I may be wrong. You may not need to squash before merging. it might be done automatically by GitHub.

**Comment by brittmol** [comment]
made fixes to method names

**Comment by brittmol** [comment]
We ran server and made it run properly - it is able to hit endpoints

**Review by Warmedpie — APPROVED** [review]
LGTM, conversation held earlier cleared up a lot of things.

**Review by wallclockbuilder — APPROVED** [review]
LGTM

**Comment by wallclockbuilder** [comment]
Can confirm squash and merge works. No need to squash manually. 
Screenshot 2024-08-07 at 2 45 46 PM

**Pull request merged**
