### PR TITLE
Structure for API Tests.

### PR DESCRIPTION
**Pull request by wallclockbuilder**

### CODE REVIEW

**Comment by wallclockbuilder** [comment]
Moved the tests into the main file and also pulled in main.

**Review by WaiyatHamdani — APPROVED** [review]
looks good

**Review by Warmedpie — DISMISSED** [review]
Please handle merge conflicts before further review.

**Comment by LiquidPlummer** [comment]
Looks good to me, weirdly the conflicts were not present when I pulled it down.

**Review by LiquidPlummer — APPROVED** [review]

**Review by Warmedpie — APPROVED** [review]
LGTM

**Pull request merged**
